### PR TITLE
Sqs endpoint

### PR DESCRIPTION
**Pull request by lennycampino**
Added sqs aws endpoint

### CODE REVIEW

**Comment by tidwall** [comment]
Thanks for the PR. I haven't had an opportunity to review on a active SQS endpoint yet but I'll keep you posted as soon as do.

**Comment by lennycampino** [comment]
Okay, thank you

**Comment by tidwall** [comment]
No worries. I’m still reviewing and I’ll let you know if there’s anything big that needs to be changed.

**Comment by tidwall** [comment]
Thanks for PR!

**Pull request merged**
