### PR TITLE
Strictly check if values passed to JSET are numbers

### LINKED ISSUE #249: tile38-1.10.1 build broken under FreeBSD
I try to update tile38 from 1.10.0 to 1.10.1 and get the following error:

~~~
% ./build.sh 
# runtime
/usr/local/go/src/runtime/signal_unix.go:28:21: _SIG_DFL redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:15:21
/usr/local/go/src/runtime/signal_unix.go:29:21: _SIG_IGN redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:16:21
/usr/local/go/src/runtime/signal_unix.go:39:5: fwdSig redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:25:5
/usr/local/go/src/runtime/signal_unix.go:50:2: disableSigChan redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:35:2
/usr/local/go/src/runtime/signal_unix.go:51:2: enableSigChan redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:36:2
/usr/local/go/src/runtime/signal_unix.go:52:2: maskUpdatedChan redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:37:2
/usr/local/go/src/runtime/signal_unix.go:64:5: signalsOK redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:49:5
/usr/local/go/src/runtime/signal_unix.go:70:22: initsig redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:55:22
/usr/local/go/src/runtime/signal_unix.go:108:38: sigInstallGoHandler redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:90:37
/usr/local/go/src/runtime/signal_unix.go:136:20: sigenable redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal1_unix.go:115:20
/usr/local/go/src/runtime/signal_unix.go:136:20: too many errors
~~~

My env:
~~~
% uname -mrs
FreeBSD 12.0-CURRENT amd64
~~~

~~~
% go version
go version go1.9.2 freebsd/amd64
~~~

Previous releases (including 1.10.0)  did not have any problem.

### LINKED ISSUE #493: JGET returns invalid JSON when JSET sends strings that look like numbers
```
$ telnet localhost 9851
Trying ::1...
Connected to localhost.
Escape character is '^]'.
JSET user 901 name 0236
+OK
jget user 901
$13
{"name":0236}
JSET user 901 name "0236"
+OK
jget user 901
$13
{"name":0236}
```
The trouble is that `{"name":0236}` is not strictly valid JSON and is rejected by the Jackson parser (https://github.com/FasterXML/jackson)

Is there syntax that will force JSET to treat the value as a string?

### PR DESCRIPTION
**Pull request by JordanArmstrong**
This PR adds a new function that validates if a string is a number according to the JSON spec, replacing the call to ParseFloat. This fixes #493

This is my first experience with Go, so please let me know if I did something wrong, or if there is a more idiomatic way of doing things.

### CODE REVIEW

**Comment by tidwall** [comment]
Looks good. 

Is the `isJsonNumber` your code? If it came from another project I want to make sure there's proper attribution. Otherwise we can plop in a modification of https://github.com/tidwall/gjson/blob/master/gjson.go#L2482-L2549

Thanks

**Comment by stevelacy** [comment]
would be nice if this was exported: https://golang.org/src/encoding/json/decode.go?s=7038:7056#L202

**Comment by tidwall** [comment]
@stevelacy I agree

**Comment by JordanArmstrong** [comment]
It's my code, but a modification of the code you posted might be better, it's probably better tested. Or copying the code from golang with attribution if you're ok with that.

**Comment by JordanArmstrong** [comment]
I've replaced the code with a modified version of what gjson. I figure that code is better exercised and is easier to read through.

**Comment by tidwall** [comment]
Please ignore the commit 55e668e that is referencing this PR in the commit message. That was my mistake. It should be referencing #502.

**Pull request merged**
