### PR TITLE
Add FreeBSD packaging. Tested on FreeBSD 10,11 x86_64

### PR DESCRIPTION
**Pull request by olevole**
Hi,

Also, I've create the tile38 port for FreeBSD platform: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210147
And test iе щт various active FreeBSD version. Looks like all fine. It would be nice to mention the possibility of using your product on FreeBSD platform with installing from packages:

~~~
pkg install tile38
~~~

or from the ports:
~~~
make -C /usr/ports/databases/tile38 install
~~~

or via curl as usual for other OSes, when package tile38-1.2.0-freebsd-amd64.zip will be done

### CODE REVIEW

**Comment by tidwall** [comment]
This is great. Yes I will mention FreeBSD and add install instruction to the website and README. I'm assuming that the curl/untar operations for FreeBSD work the same as Linux?

**Comment by olevole** [comment]
Yes, with **tar xfz** behavior is equal on FreeBSD. 

BTW, any plan to make the ability to specify the pidfile via args? In current version i use 
~~~
daemon -p <PID>
~~~

to store tile38-server pid file. Pid file is necessary for stop/status operation:

service tile38 stop << just send kill HUP in my version

**Comment by tidwall** [comment]
I agree and created a new issue #20.

**Comment by olevole** [comment]
Great! Thank you very much!

**Comment by tidwall** [comment]
I just added the instructions to the [tile38.com](http://tile38.com) homepage, and added a FreeBSD binary package to the Github releases page. 

Thanks a ton for you help!

**Pull request merged**
