### PR TITLE
[WIP] Added distance to NEARBY command

### PR DESCRIPTION
**Pull request by m1ome**
**Work in progress**
Implementing #112 feature.

Need to get some thoughts, @tidwall!
Idk, if i am doing this in way you wanna to make this feature up.

Btw, great tool! Love it a lot!

### CODE REVIEW

**Comment by tidwall** [comment]
@m1ome Thanks for the kind words and the solid PR. I really like the refactoring of the scan writer params. It's now much easier to understand and future-proof.

**Comment by m1ome** [comment]
@tidwall just give me a thoughts how you wanna this feature to look like, and i can change PR accordingly to your vision.

**Comment by tidwall** [comment]
@m1ome One minor detail, there's the file [core/commands.json](https://github.com/tidwall/tile38/blob/master/core/commands.json#L454) which contains a list of all the commands and keywords for Tile38. This file is resourced by the `tile38-cli` help menu and the [tile38.com](http://tile38.com/commands/nearby) website.

It needs to be updated to include the new `DISTANCE` keyword. The steps are:

1. update the json.
2. execute `core/gen.sh`
3. do a `make test`

**Comment by m1ome** [comment]
@tidwall done

**Pull request merged**
