### PR TITLE
fixed missing else statement when creating nats connection

### PR DESCRIPTION
**Pull request by lennycampino**
Hi,

I forgot an else statement... And could you please push the newest version to the docker hub ? Would be nice.

### CODE REVIEW

**Comment by tobilg** [comment]
Afaik every master push will be pushed to the `edge` tag on Docker Hub.

**Comment by tidwall** [comment]
@lennycampino

Please verify that the `edge` docker image is working for you. There's a scheduled release coming up in the next week that will include your change.

Also could you update the [webhooks docs](http://tile38.com/commands/sethook/) on the Tile38 documentation site to include the nats endpoint? 

The doc repo is https://github.com/tile38/tile38.github.io

Thanks again.

**Comment by lennycampino** [comment]
Okay thank you and yes i can update the webhook docs.

**Comment by tidwall** [comment]
Thanks. I just pushed your doc update

**Pull request merged**
