### PR TITLE
Add wherein command

### PR DESCRIPTION
**Pull request by rshura**

### CODE REVIEW

**Comment by tidwall** [comment]
Looks good and works from my side. We'll need to add some tests and update the core package before merging.

You can add a test to one of the `_test.go` files in the `test` directory. I think just adding a new entry to 
https://github.com/tidwall/tile38/blob/master/tests/keys_test.go#L17 should be fine.

To update core, edit the `core/commands.json` file and add the WHEREIN keyword for the commands that use it. Then run `core/gen.sh` to refresh the Go files. This will update the `tile38-cli` autocomplete and help menus. Also the tile38.com website uses core to help with populating the commands with the correct fields.

Thanks!

**Comment by rshura** [comment]
Makes sense, however I'm unclear on how to express `WHEREIN` syntax in `commands.json` file, because `WHEREIN` will take an unknown number of values.  Should I just use `["field","num_vals", "val0", "val1", "..."]`?

**Comment by tidwall** [comment]
I had to make a quick update to the master branch to allow for a variable number of values on the last argument.

Adding the following to a command arguments should work:

```json
      {
        "command": "WHEREIN",
        "name": ["field","count","value"],
        "type": ["string","integer","double"],
        "optional": true,
        "multiple": true,
        "variadic": true
      },
```
... which will print:

```
[WHEREIN field count value [value ...] ...]
```

**Comment by rshura** [comment]
Great, thanks!

How do I run the tests?

**Comment by tidwall** [comment]
`make test` from root will do a full build and run all tests. It's exhaustive and slow. If you are only modifying _test.go files in the `tests` directory then I recommend cd'ing into the tests directory and running `go test`.

**Comment by tidwall** [comment]
Merged. :)

**Comment by rshura** [comment]
Thanks!  Should I also update the docs now?

**Comment by tidwall** [comment]
Sure. The https://github.com/tile38/tile38.github.io repo is the tile38.com website.

We probably just need to add a description about the WHEREIN option to the src/website/root/commands/intersects.md file.

Then run the `./build.sh` to generate the site. 
Or `./build.sh -port 8080` to generate and test at http://localhost:8080/

**Pull request merged**
