### PR TITLE
Redis endpoint for webhooks

### PR DESCRIPTION
**Pull request by m1ome**
Resolving #108 (Redis enpoint for webhooks)

**Redis**
The `redis://` provides support for sending messages to **Redis** *PUBSUB* channels.  
For example:
```redis
SETHOOK warehouse disque://10.0.20.78:6379/warehouse
```

All webhook messages should be send to the Redis server at 10.0.20.78:6379 in a [PUBSUB](https://redis.io/commands#pubsub) queue to a **warehouse** channel.

### CODE REVIEW

**Comment by m1ome** [comment]
@tidwall need your review.

**Comment by phulst** [comment]
awesome! thanks m1ome

**Comment by m1ome** [comment]
@phulst you are welcome!

**Comment by tidwall** [comment]
@m1ome This is a wonderful addition!

**Pull request merged**
