### PR TITLE
[FIX] Error string should not be capitalized or end with punctuation

### PR DESCRIPTION
**Pull request by im-kulikov**

### CODE REVIEW

**Comment by im-kulikov** [comment]
@tidwall hi there! Any updates?

**Comment by tidwall** [comment]
These changes break user functionality. Please refrain from filing PRs without discussing the change beforehand. 
Thanks.

**Comment by im-kulikov** [comment]
Where I can discuss for changes?

**Comment by tidwall** [comment]
File an issue or Gitter.

**Comment by im-kulikov** [comment]
Oh.. okay

**Pull request closed without merging**
