### PR TITLE
Resolve 0 value fields in RESPONSE

### PR DESCRIPTION
**Pull request by m1ome**
Resolving #169 

We need to think if we need this one.

### CODE REVIEW

**Comment by tidwall** [comment]
The only issue I see with this change is that it's possible that zero fields are returned for elements that never set them.

```
set mykey id1 field a 1 point 10 10
set mykey id2 field b 2 point 20 20
set mykey id3 field a 3 point 30 30
```

```json
get mykey id2 withfields
{"ok":true,"object":{"type":"Point","coordinates":[20,20]},
"fields":{"a":0,"b":2},"elapsed":"40.304µs"}
```

`id2` now returns zero for field `a` even though it never set the field.

**Comment by Lars-Meijer** [comment]
I think the current implementation is better, if value is not there, it is up to the application to decide what to do with the missing field, either assume it is 0, or assume it doesn't exist. 

This fix solves nothing, since there is still no way of making a difference between the two cases.

**Comment by m1ome** [comment]
That's why i said i don't know if this one fixes problem at all.

**Comment by tidwall** [comment]
@m1ome Thanks a bunch for the PR. It's provided food for thought, but I think that it's best not to merge at this time. I would rather not change the current behavior unless it solves the the bigger issue of detecting fields that are set, not-set, and zero.

**Pull request closed without merging**
