### PR TITLE
JSON logging

### PR DESCRIPTION
**Pull request by iwpnd**
Hi 👋 

as discussed on Slack I drafted a possible use of the zap logger in Tile38 that can be enabled upon starting the server.
Using an advanced flag `--logjson` I set `LogJSON` in `internal/log/log.go` to `true`, get a default config and build the zap logger. 

I'm piggybacking your existing log functions. If `LogJSON == true` the log will be json. If not, it will use the existing logging. 

The `DEFAULT_CONFIG` is something to discuss, like what to include and how to format it. 
Or you choose to use Zaps [opinionated production defaults](https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/config.go#L98) that stray away from your text logs. In the end it comes down to personal preference I guess. 

There's also the possibility to remove your logging for zap entirely, as it also provides `console` as a possible encoder option that allows to log as text, similar to right now with a little more flexibility on how to configure the output.

I also did not yet include the possibility to add a custom configuration file that can be passed along in Tile38s configuration file.

Would love to get some feedback on this first. :)

### CODE REVIEW

**Comment by tidwall** [comment]
I gave it a spin and it mostly looks good.

Should we conditionally omit the title message when --jsonlog is provided?

```if !jsonlog {```
```
   _____ _ _     ___ ___
  |_   _|_| |___|_  | . |  Tile38 1.26.4 (ffb5526f) 64 bit (amd64/darwin)
    | | | | | -_|_  | . |  Port: 9851, PID: 98638
    |_| |_|_|___|___|___|  tile38.com

Please consider sponsoring Tile38 development, especially if your company
benefits from this software. Visit tile38.com/sponsor today to learn more.
```
```}```

**Comment by tidwall** [comment]
> I'm piggybacking your existing log functions. If LogJSON == true the log will be json. 

I agree with this approach. 

> The DEFAULT_CONFIG is something to discuss, like what to include and how to format it.
> Or you choose to use Zaps opinionated production defaults that stray away from your text logs. In the end it comes down to personal preference I guess.

I'm fine with straying away from the text logs format altogether. It's old fashioned. If someone chooses to use the `--logjson` option then I think it's fair to guess that they want a little more control over the output. Using Zaps  opinionated production defaults would be a reasonable start. 

> I also did not yet include the possibility to add a custom configuration file that can be passed along in Tile38s configuration file.

Perhaps we just allow for a `"logjson"` field to the current Tile38 config file. This  If the field is present then `--logjson` is automatically chosen and the child members of the field can define the options.

```jsonc
{
  "server_id": "325969f011c8a2da15e2418c3e212cf3",
  "logjson": {
     // .. fancy json logging options .. //
  }
}
```

> There's also the possibility to remove your logging for zap entirely, as it also provides console as a possible encoder option that allows to log as text, similar to right now with a little more flexibility on how to configure the output.

I'm fine with this too. As long as it doesn't break compatibility with current users.

**Comment by iwpnd** [comment]
Hey @tidwall, thank you for your feedback. I'm currently recovering from a Covid infection, but I plan on finishing this PR as soon as I'm able to. :)

**Comment by iwpnd** [comment]
Hey @tidwall 

I added a `logconfig` child to the server config that'll take a zap.Config such as this:

```json
{
  "level": "debug",
  "encoding": "json", 
  "outputPaths": ["stdout", "/tmp/logs"],
  "errorOutputPaths": ["stderr"],
  "initialFields": {"foo": "bar"},
  "encoderConfig": {
    "messageKey": "message",
    "levelKey": "level",
    "levelEncoder": "lowercase"
  }
}
```

If the child is present in the server config, it'll be used. If it is not present but `--logjson` is set, it'll fallback to the default `zap.NewProductionConfig()`.

I have a little chicken and egg situation tho. 
Say I start tile38 with `tile38-server -vv -d data/` and a `logconfig` child in the `server.Config` we first see text logs, up until the point where the config is loaded in `server.Serve`.
Another situation is when I start with `tile38-server -vv -d data/ --logjson` it'll start with the default config, up until the config is loaded in `server.Serve`.

A solution would be either a separate config file for the logger, access to `config.loadConfig` from within the log package or we pass the config as an argument to `--logjson '{"logconfig": {...myconfig..}}'`

**Comment by tidwall** [comment]
Perhaps we can take a quick peek at the data/config file to see if the "logconfig" field exists before we show the first log entry.

Then allow for the 

```go
if !log.LogJSON {
	data, _ := os.ReadFile(filepath.Join(dir,"config"))
	log.LogJSON = gjson.GetBytes(data, "logconfig.encoding").String() == "json"
}

if log.LogJSON {
	log.Printf(`Tile38 %s%s %d bit (%s/%s) %s%s, PID: %d. Visit tile38.com/sponsor to support the project`,
		core.Version, gitsha, strconv.IntSize, runtime.GOARCH, runtime.GOOS, hostd, saddr, os.Getpid())
 	}

...
```

**Comment by iwpnd** [comment]
You are right, the `dir` is already provided at this point. That way the logger configuration can stay in `tile38-server/main.go` entirely.

**Comment by tidwall** [comment]
I'm good with this approach. 

A couple things I noticed. For text mode, the initial messages are tabbed over.

```
		_____ _ _     ___ ___
		|_  _|_| |___|_  | . |	Tile38 1.26.4 (407fd4c7) 64 bit (amd64/darwin)
		 | | | | | -_|_  | . |  Port: 9851, PID: 63074
		 |_| |_|_|___|___|___|  tile38.com

	 Please consider sponsoring Tile38 development, especially if your company
	 benefits from this software. Visit tile38.com/sponsor today to learn more.

	 2021/12/27 11:19:57 [INFO] Server started, Tile38 version 1.26.4, git 407fd4c7
2021/12/27 11:19:57 [INFO] AOF loaded 23 commands: 0.00s, 177458/s, 9 MB/s
```

For json mode, the "caller" field only give the file and line number of the wrapped log function. Can we remove this?

```
{"level":"info","ts":1640629125.618154,"caller":"log/log.go:119","msg":"Tile38 1.26.4 (407fd4c7) 64 bit (amd64/darwin) Port: 9851, PID: 62931. Visit tile38.com/sponsor to support the project"}
{"level":"info","ts":1640629125.618237,"caller":"log/log.go:119","msg":"Server started, Tile38 version 1.26.4, git 407fd4c7"}
{"level":"debug","ts":1640629125.62014,"caller":"log/log.go:207","msg":"Geom indexing: QuadTree (64 points)"}
{"level":"debug","ts":1640629125.62016,"caller":"log/log.go:207","msg":"Multi indexing: RTree (64 points)"}
{"level":"info","ts":1640629125.620596,"caller":"log/log.go:119","msg":"AOF loaded 23 commands: 0.00s, 116290/s, 6 MB/s"}
```

**Comment by iwpnd** [comment]
@tidwall you're right. I disabled the caller for both a custom config, and the default config. I also fixed the start screen and the first log.

**Comment by tidwall** [comment]
Looks good. I made one minor change to make the log calls inlined. This is mostly so that the vast number of `log.Debug` calls can be inlined.

**Comment by iwpnd** [comment]
Awesome, thanks! I added a new section on the documentation page with https://github.com/tile38/tile38.github.io/pull/52 if you want to take a look. Thought I'd use the chance to go a little more into detail on the configuration file while I'm at it.

**Pull request merged**
