### PR TITLE
Added MQTT endpoint

### PR DESCRIPTION
**Pull request by m1ome**
**Agenda**

Issue: #154 
Idea: Add MQTT endpoint webhook(s)

**Usage**
```
SETHOOK mqtt mqtt://127.0.0.1/tile NEARBY fleet FENCE POINT 30 30 500
```

**Result**
```
{"command":"set","group":"58bf23c97784046c74493147","detect":"inside","hook":"mqtt","key":"fleet","time":"2017-03-08T00:19:05.888021614+03:00","id":"truck1","object":{"type":"Point","coordinates":[30,30]}}
```

**TODO**
- [x]  QoS support
- [x]  Retained

**Testing**
- Install [mosquito](https://mosquitto.org)
- Install [MQTT.fx](http://www.jensd.de/apps/mqttfx/1.3.1/)
- ...
- Profit!

@tidwall any thoughts?

### CODE REVIEW

**Comment by tidwall** [comment]
@m1ome I'm gonna need to spend some time with MQTT and learn about it a little more, but from a cursory glance your code looks good.

**Comment by m1ome** [comment]
@tidwall no need to rush, implemented QoS and retained. But I will spend some time testing it also. Just get some simple tests. I am also not a specialist in MQTT :)

**Comment by tidwall** [comment]
@m1ome sounds good. thanks.

**Comment by m1ome** [comment]
@tidwall resolved conflicts on this one.

**Pull request merged**
