### PR TITLE
[WIP] Implemented NEARBY distance sort

### PR DESCRIPTION
**Pull request by m1ome**
**Work in progress** DON'T MERGE RIGHT NOW!

Hacky and simple solution to implement #130 
This is should resolve our need right now in this feature, but in future we should remove this hacky way, changing it to KNN solution (also we should refactor distance calculation, yay!)

Right now i will write some performance tests on 1M, 3M, 5M records.
After measuring performance we will be able to make a decision `To merge or not to merge`.

@tidwall your thoughts about it?!

Hamlet

### CODE REVIEW

**Comment by tidwall** [comment]
Awesome!! I'll review asap and let you know.

**Comment by m1ome** [comment]
@tidwall 

Benchmark repo: https://github.com/m1ome/tile38-benchmark

**Benchmark results:**
```
BenchmarkNearby1M-8                       	   10000	    193772 ns/op
BenchmarkNearbyWithLimit1M-8              	    5000	    205370 ns/op
BenchmarkNearbyWithLimitAndDistance1M-8   	   30000	     47811 ns/op
BenchmarkNearby3M-8                       	   10000	   1543568 ns/op
BenchmarkNearbyWithLimit3M-8              	    1000	   1754289 ns/op
BenchmarkNearbyWithLimitAndDistance3M-8   	    3000	   1701185 ns/op
BenchmarkNearby5M-8                       	    1000	   1765802 ns/op
BenchmarkNearbyWithLimit5M-8              	    1000	   1813574 ns/op
BenchmarkNearbyWithLimitAndDistance5M-8   	    1000	   1786435 ns/op
```

**Comment by m1ome** [comment]
@tidwall this is pretty strange results, btw. How can it be that filtering up with distance & limit is faster than just limit? and faster than stuff without limit?

**Comment by tidwall** [comment]
Not sure about why which is faster, but I'm taking a cursory scan of the code and wondering about your inputs.

You are executing a [NEARBY search on a point](https://github.com/m1ome/tile38-benchmark/blob/master/benchmark_test.go#L19) that's outside of the `{-180,-90}{+180,+90}` boundary. Tile38 accepts out of bounds points, but it must [normalize](https://github.com/tidwall/tile38/blob/5ec3111e8ba92e07b4ed1b588a479e185cacd3c9/index/norm.go#L7) the point prior to executing, which can be a little more expensive.

Also all the points that in the database appear to be in the [same location](https://github.com/m1ome/tile38-benchmark/blob/master/gen.go#L32) `100,100`, which too must be normalized. 

The other thing is that if you add millions of points as the same position, the RTree won't optimize very well and you affectively create a scan scenario.

I suggest adding a little randomization to the inputs that keeps all points within a bounding area. This will be more like a real-world scenario.

[Here's an example](https://github.com/tidwall/tile38/blob/master/controller/dev.go#L21).

I'm guessing that your results will be a little different after randomizing.

**Comment by m1ome** [comment]
@tidwall updated benchmark code

Results:
```
BenchmarkNearby1M-8                       	    2000	    652743 ns/op
BenchmarkNearbyWithLimit1M-8              	    2000	    684385 ns/op
BenchmarkNearbyWithLimitAndDistance1M-8   	   30000	     50146 ns/op
BenchmarkNearby3M-8                       	    3000	    638567 ns/op
BenchmarkNearbyWithLimit3M-8              	    2000	    688303 ns/op
BenchmarkNearbyWithLimitAndDistance3M-8   	   30000	     49769 ns/op
BenchmarkNearby5M-8                       	    3000	    660572 ns/op
BenchmarkNearbyWithLimit5M-8              	    3000	    667264 ns/op
BenchmarkNearbyWithLimitAndDistance5M-8   	   30000	     52020 ns/op
```

**Comment by m1ome** [comment]
@tidwall this is starting to be more and more interesting. 👓

**Comment by m1ome** [comment]
@tidwall need to investigate why this is happening, this is kinda strange that sorted fullscan goes faster than limit.

**Comment by tidwall** [comment]
@m1ome That sounds strange to me too.

**Comment by m1ome** [comment]
@tidwall found a problem i run this one on old server version. :man_facepalming: 

Correct results:
```
BenchmarkNearby1M-8                       	    3000	    614763 ns/op
BenchmarkNearbyWithLimit1M-8              	    3000	    641573 ns/op
BenchmarkNearbyWithLimitAndDistance1M-8   	      10	 116712954 ns/op
BenchmarkNearby3M-8                       	    2000	    660310 ns/op
BenchmarkNearbyWithLimit3M-8              	    2000	    632736 ns/op
BenchmarkNearbyWithLimitAndDistance3M-8   	       3	 373100161 ns/op
BenchmarkNearby5M-8                       	    2000	    750094 ns/op
BenchmarkNearbyWithLimit5M-8              	    2000	    666306 ns/op
BenchmarkNearbyWithLimitAndDistance5M-8   	       2	 644637318 ns/op
```

**Comment by tidwall** [comment]
Ah. That looks more accurate. :)

**Comment by m1ome** [comment]
It looks like it's 300 times less effective right now with 1M records scan.

On my machine it takes ~ `92.902702ms` to fullscan 1M records with **LIMIT** + **DISTANCE**.
Idk if this way should be in production.

This is kinda slow right now, it's only your decision to take this into production or not.

**Comment by m1ome** [comment]
@tidwall and it drops down with records grow equally on 3M it will drops down to 600 times less effective

**Comment by tidwall** [comment]
I agree that may not be fast enough for production.

**Comment by m1ome** [comment]
@tidwall sound like we should focus on KNN to resolve this feature.

**Comment by tidwall** [comment]
Yeah. KNN is the way to go for sure.

**Comment by m1ome** [comment]
@tidwall let's close this one. I think it's not worth it.

**Comment by tidwall** [comment]
Thanks for researching this. I'll take a stab at the KNN over the next couple days. I'll close this for now, but these benchmarks will be helpful in the future.

**Pull request closed without merging**
