### PR TITLE
AMQP webhook

### PR DESCRIPTION
**Pull request by m1ome**
**Agenda**
Issue: #157 
Support: 0.9.1 AMQP protocol (RabbitMQ)

**Libraries**
AMQP: [streadway/amqp](https://github.com/streadway/amqp)

**Prerequisites**
1. [RabbitMQ](https://www.rabbitmq.com)
2. RabbitMQ [Management tool](https://www.rabbitmq.com/management.html)

**Work logic**
1. Connect to RabbitMQ
2. Create Exchange named <EXCHANGE_NAME>
3. Create Queue named <EXCHANGE_NAME>
4. Create RouteKey<ROUTE_KEY:[tile38]> binded from Exchange <EXCHANGE_NAME> to Queue <EXCHANGE_NAME> 
5. Publish into Queue <EXCHANGE_NAME> with RouteKey<ROUTE_KEY:[tile38]>

**Usage**
```
SETHOOK amqp amqp://guest:guest@127.0.0.1: 5672/tile38?route=tile NEARBY fleet FENCE POINT 30 30 500
```

**Message**
`Content-Type` is `application/json`

```
{"command":"set","group":"58c6ba02778404601d4927d1","detect":"inside","hook":"amqp","key":"fleet","time":"2017-03-13T18:28:22.628925432+03:00","id":"truck1","object":{"type":"Point","coordinates":[30,30]}}
```

`route` - is optional parameter, by default it equals to `tile38`

**Defaults**
`type` - 'direct'
`durable` - true
`immediate` - false
`mandatory` - false
`auto_delete` - false
`internal` - false
`no_wait` - false
`delivery_mode` - 1
`route` - `tile38`

@tidwall wanna your thoughts about it.

### CODE REVIEW

**Comment by paavalan** [comment]
@m1ome everything looks good, thanks

**Comment by tidwall** [comment]
@m1ome I hope to get to testing and merging soon. Thanks for your patience.

**Comment by m1ome** [comment]
@tidwall don't worry all is fine 👍

**Comment by tidwall** [comment]
On my Mac I installed RabbitMQ
```sh
$ brew install rabbitmq
```
Started the server
```sh
$ /usr/local/sbin/rabbitmq-server
```
Added the simple hook
```
TILE38> SETHOOK amqp amqp://guest:guest@localhost:5672/tile38 NEARBY fleet FENCE POINT 30 30 500
```
Added a point
```
TILE38> ADD fleet asdf POINT 30 30
```
Then read the message off of the RabbitMQ queue
```sh
$ rabbitmqadmin get queue=tile38 requeue=false
```


```
+-------------+----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+------------------+-------------+
| routing_key | exchange | message_count |                                                                                                   payload                                                                                                    | payload_bytes | payload_encoding | redelivered |
+-------------+----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+------------------+-------------+
| tile38      | tile38   | 0             | {"command":"set","group":"58c97adcd5eefdab69f686a3","detect":"outside","hook":"amqp","key":"fleet","time":"2017-03-15T10:35:14.408150365-07:00","id":"asdf","object":{"type":"Point","coordinates":[31,30]}} | 204           | string           | False       |
+-------------+----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+------------------+-------------+
```

I think this is a good start. I'm merging shortly.

**Comment by paavalan** [comment]
@m1ome @tidwall  thanks. sounds good.

**Comment by Lars-Meijer** [comment]
When connecting goes wrong there is no way to get feedback, is this intended behavior and is this also the case for other connectors like Kafka?

**Comment by m1ome** [comment]
@Lars-Meijer you can use `-vv` to make sure all stuff connected correctly

**Comment by Lars-Meijer** [comment]
Thanks will test that sometime later 👍

**Comment by m1ome** [comment]
@tidwall I can do this portion of logging, just make an issue and set this to me.

**Pull request merged**
