### PR TITLE
[FIX] Cleanup code

### PR DESCRIPTION
**Pull request by im-kulikov**
- import sorting
- omit type
- remove unused wrap

### CODE REVIEW

**Comment by im-kulikov** [comment]
@tidwall hi there! Any updates?

**Comment by tidwall** [comment]
Sorry, but no thanks at this time.

**Comment by im-kulikov** [comment]
Hm.. why? This doesn’t break any functionality.. imports not sorted.. few of types can be omitted

**Comment by tidwall** [comment]
I may address code formatting in the future, but right now this change is only syntactic and doesn’t fix anything user facing.

**Comment by im-kulikov** [comment]
Ok..

**Pull request closed without merging**
